/* Turn a finished workbook into a CodePen.

   The engine is not touched and nothing is hosted: the .xlsx rides in the page
   as base64 and is handed to the public loadExcelFile(), which is the same call
   the File menu makes. So a model that is settled can be shown by pasting one
   file into the HTML panel, with no server, no CORS and no data file.

     node tools/mkpen.js MODEL.xlsx [out.html] [--pin <commit>]

   Base64 runs about 4/3 of the file, and CodePen is happy with a few hundred
   KB of HTML, so anything up to roughly a 300 KB workbook is comfortable. Past
   that, fetch it from a CORS-enabled host instead.                         */
const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2).filter(a => a !== '--pin');
const pinAt = process.argv.indexOf('--pin');
const PIN = pinAt > -1 ? process.argv[pinAt + 1] : 'main';
const IN = args[0];
if (!IN) { console.error('usage: node tools/mkpen.js MODEL.xlsx [out.html] [--pin <commit>]'); process.exit(1); }
const OUT = args[1] && args[1] !== PIN ? args[1] : IN.replace(/\.xlsx$/i, '_pen.html');
const NAME = path.basename(IN);

const buf = fs.readFileSync(IN);
/* wrapped with backslash continuations so the pen stays scrollable rather than
   one endless line; the loader strips whitespace before decoding anyway */
const b64 = buf.toString('base64').match(/.{1,120}/g).join('\\\n');

const html = `<meta charset="utf-8">
<!-- PLATE3D — ${NAME}
     Nothing here changes the engine: the workbook is carried in the page as
     base64 and handed to the public loadExcelFile(), the same call the File
     menu makes. PLATE_DATA = {} keeps the built-in tower crane from flashing
     up first. Generated by tools/mkpen.js. -->
<script src="https://unpkg.com/three@0.147.0/build/three.min.js"></script>
<script src="https://unpkg.com/three@0.147.0/examples/js/controls/OrbitControls.js"></script>
<script src="https://unpkg.com/polybooljs@1.1.0/dist/polybool.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/exceljs/4.3.0/exceljs.min.js"></script>

<script>window.PLATE_DATA = {};</script>
<script src="https://cdn.jsdelivr.net/gh/macroBIM/macroBIM@${PIN}/plate3d/plate_builder.js"></script>

<script>
var BOOK = "\\
${b64}";
window.addEventListener("load", function () {
  var bin = atob(BOOK.replace(/\\s/g, "")), u8 = new Uint8Array(bin.length);
  for (var i = 0; i < bin.length; i++) u8[i] = bin.charCodeAt(i);
  plateBuilder.loadExcelFile(new File([u8], ${JSON.stringify(NAME)}));
});
</script>
`;
fs.writeFileSync(OUT, html);
console.log(NAME + '  ' + buf.length.toLocaleString() + ' bytes  ->  ' +
            OUT + '  ' + Buffer.byteLength(html).toLocaleString() + ' bytes' +
            '   engine pinned at @' + PIN);
